SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO c VALUES('agenda_supervisor', 1, 'id_agenda', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('agenda_supervisor', 2, 'fecha', 'date', 'NO', NULL, NULL);
INSERT INTO c VALUES('agenda_supervisor', 3, 'id_coordinador', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('agenda_supervisor', 4, 'id_horario', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('agenda_supervisor', 5, 'estado', 'tinyint', 'NO', NULL, NULL);
INSERT INTO c VALUES('agenda_supervisor', 6, 'prioridad', 'tinyint', 'NO', NULL, NULL);
INSERT INTO c VALUES('alumno', 1, 'id_alumno', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('alumno', 2, 'matricula', 'varchar', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('alumno', 3, 'usuario_id', 'int', 'YES', 'NULL', 'UNIQUE');
INSERT INTO c VALUES('alumno', 3, 'usuario_id', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('alumno', 4, 'id_carrera', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('carrera', 1, 'id_carrera', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('carrera', 2, 'nombre', 'varchar', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('carrera', 3, 'id_incorporacion', 'tinyint', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('carrera_grupo', 1, 'id_carrera', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('carrera_grupo', 1, 'id_carrera', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('carrera_grupo', 2, 'id_grupo', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('carrera_grupo', 2, 'id_grupo', 'int', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('carrera_grupo', 2, 'id_grupo', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('carrera_materia', 1, 'id_carrera', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('carrera_materia', 1, 'id_carrera', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('carrera_materia', 2, 'id_materia', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('carrera_materia', 2, 'id_materia', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('ciclo_escolar', 1, 'id_ciclo', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('ciclo_escolar', 2, 'anio', 'smallint', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('ciclo_escolar', 3, 'id_periodo', 'tinyint', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('ciclo_escolar', 3, 'id_periodo', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('coordinador', 1, 'id_coordinador', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('coordinador', 2, 'usuario_id', 'int', 'YES', 'NULL', 'UNIQUE');
INSERT INTO c VALUES('coordinador', 2, 'usuario_id', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('coordinador_carrera', 1, 'id_coordinador', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('coordinador_carrera', 1, 'id_coordinador', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('coordinador_carrera', 2, 'id_carrera', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('coordinador_carrera', 2, 'id_carrera', 'int', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('coordinador_carrera', 2, 'id_carrera', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('criterios_evaluacion', 1, 'id_evacriterio', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('criterios_evaluacion', 2, 'descripcion', 'text', 'NO', NULL, NULL);
INSERT INTO c VALUES('criterios_evaluacion', 3, 'id_rubro', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('criterios_supervision', 1, 'id_supcriterio', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('criterios_supervision', 2, 'descripcion', 'text', 'NO', NULL, NULL);
INSERT INTO c VALUES('criterios_supervision', 3, 'id_rubro', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('docente', 1, 'id_docente', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('docente', 2, 'usuario_id', 'int', 'YES', 'NULL', 'UNIQUE');
INSERT INTO c VALUES('docente', 2, 'usuario_id', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('docente', 3, 'grado_academico', 'varchar', 'NO', NULL, NULL);
INSERT INTO c VALUES('docente_materia', 1, 'id_docente', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('docente_materia', 1, 'id_docente', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('docente_materia', 2, 'id_materia', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('docente_materia', 2, 'id_materia', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('evaluacion_criterios', 1, 'id_evaluacion', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('evaluacion_criterios', 1, 'id_evaluacion', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('evaluacion_criterios', 2, 'id_evacriterio', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('evaluacion_criterios', 2, 'id_evacriterio', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('evaluacion_criterios', 3, 'estado', 'tinyint', 'NO', NULL, NULL);
INSERT INTO c VALUES('evaluacion_docente', 1, 'id_evaluacion', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('evaluacion_docente', 2, 'id_alumno', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('evaluacion_docente', 3, 'id_grupo', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('evaluacion_docente', 4, 'id_docente', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('evaluacion_docente', 5, 'id_agenda', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('grupo', 1, 'id_grupo', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('grupo', 2, 'acronimo', 'varchar', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('grupo', 3, 'id_ciclo', 'int', 'YES', 'NULL', 'UNIQUE');
INSERT INTO c VALUES('grupo', 3, 'id_ciclo', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('grupo', 4, 'id_turno', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('grupo', 5, 'id_modalidad', 'tinyint', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('grupo', 6, 'id_nivel', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('grupo', 7, 'id_carrera', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('horario', 1, 'id_horario', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('horario', 2, 'id_ciclo', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('horario', 3, 'id_dia', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('horario', 4, 'hora_inicio', 'time', 'NO', NULL, NULL);
INSERT INTO c VALUES('horario', 5, 'hora_fin', 'time', 'NO', NULL, NULL);
INSERT INTO c VALUES('inscripcion_grupo', 1, 'id_grupo', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('inscripcion_grupo', 1, 'id_grupo', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('inscripcion_grupo', 2, 'id_alumno', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('inscripcion_grupo', 2, 'id_alumno', 'int', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('inscripcion_grupo', 2, 'id_alumno', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('login_usuario', 1, 'id_log', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('login_usuario', 2, 'id_usuario', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('login_usuario', 3, 'actividad', 'text', 'NO', NULL, NULL);
INSERT INTO c VALUES('login_usuario', 4, 'fecha', 'timestamp', 'YES', 'current_timestamp()', NULL);
INSERT INTO c VALUES('materia', 1, 'id_materia', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('materia', 2, 'nombre', 'varchar', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('materia', 3, 'id_nivel', 'tinyint', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('materia', 3, 'id_nivel', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('materia_horario', 1, 'id_materia', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('materia_horario', 1, 'id_materia', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('materia_horario', 2, 'id_horario', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('materia_horario', 2, 'id_horario', 'int', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('materia_horario', 2, 'id_horario', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel', 1, 'id_plantel', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('plantel', 2, 'nombre', 'varchar', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('plantel', 3, 'ubicacion', 'varchar', 'YES', 'NULL', NULL);
INSERT INTO c VALUES('plantel_carrera', 1, 'id_plantel', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('plantel_carrera', 1, 'id_plantel', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel_carrera', 2, 'id_carrera', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('plantel_carrera', 2, 'id_carrera', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel_carrera_modalidad', 1, 'id_plantel', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('plantel_carrera_modalidad', 1, 'id_plantel', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel_carrera_modalidad', 2, 'id_carrera', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('plantel_carrera_modalidad', 2, 'id_carrera', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel_carrera_modalidad', 3, 'id_modalidad', 'tinyint', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('plantel_carrera_modalidad', 3, 'id_modalidad', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel_turno', 1, 'id_plantel_turno', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('plantel_turno', 2, 'id_plantel', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel_turno', 3, 'hora_descanso', 'time', 'YES', 'NULL', NULL);
INSERT INTO c VALUES('plantel_turno', 4, 'duracion_bloques', 'int', 'NO', NULL, NULL);
INSERT INTO c VALUES('plantel_turno', 5, 'duracion_descanso', 'int', 'NO', NULL, NULL);
INSERT INTO c VALUES('plantel_turno', 6, 'id_dia', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('plantel_turno', 7, 'hora_inicio', 'time', 'NO', NULL, NULL);
INSERT INTO c VALUES('plantel_turno', 8, 'hora_fin', 'time', 'NO', NULL, NULL);
INSERT INTO c VALUES('plantel_turno', 9, 'id_turno', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('supervision_criterios', 1, 'id_supervision', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('supervision_criterios', 1, 'id_supervision', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('supervision_criterios', 2, 'id_supcriterio', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('supervision_criterios', 2, 'id_supcriterio', 'int', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('supervision_criterios', 3, 'estado', 'tinyint', 'NO', NULL, NULL);
INSERT INTO c VALUES('supervision_docente', 1, 'id_supervision', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('supervision_docente', 2, 'id_docente', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('supervision_docente', 3, 'id_agenda', 'int', 'YES', 'NULL', 'FOREIGN KEY');
INSERT INTO c VALUES('supervision_docente', 4, 'observaciones', 'text', 'YES', 'NULL', NULL);
INSERT INTO c VALUES('supervision_docente', 5, 'tema', 'text', 'NO', NULL, NULL);
INSERT INTO c VALUES('usuario', 1, 'id', 'int', 'NO', NULL, 'PRIMARY KEY');
INSERT INTO c VALUES('usuario', 2, 'nombre', 'varchar', 'NO', NULL, NULL);
INSERT INTO c VALUES('usuario', 3, 'apellido_paterno', 'varchar', 'NO', NULL, NULL);
INSERT INTO c VALUES('usuario', 4, 'apellido_materno', 'varchar', 'NO', NULL, NULL);
INSERT INTO c VALUES('usuario', 5, 'correo', 'varchar', 'NO', NULL, 'UNIQUE');
INSERT INTO c VALUES('usuario', 6, 'contrasena', 'text', 'NO', NULL, NULL);
INSERT INTO c VALUES('usuario', 7, 'id_rol', 'tinyint', 'NO', NULL, 'FOREIGN KEY');
INSERT INTO c VALUES('usuario', 8, 'fecha_registro', 'timestamp', 'NO', 'current_timestamp()', NULL);
INSERT INTO c VALUES('usuario', 9, 'ultimo_acceso', 'timestamp', 'YES', 'current_timestamp()', NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
